// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RecycleRush2015.subsystems;

import org.usfirst.frc1735.RecycleRush2015.Robot;
import org.usfirst.frc1735.RecycleRush2015.RobotMap;
import org.usfirst.frc1735.RecycleRush2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class CollectorRoller extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController intakeMotorLeft = RobotMap.collectorRollerIntakeMotorLeft;
    SpeedController intakeMotorRight = RobotMap.collectorRollerIntakeMotorRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void engage(double magnitudeDirection) {
    	// "in" is negative; "out" is positive.  
    	intakeMotorLeft.set(magnitudeDirection);
    	intakeMotorRight.set(magnitudeDirection); // Assumes the left and right motors have inverted wiring
    }
    
    // These functions use the collector wheels to push the robot sideways along a wall surface for lining up to the tote chute
    public void wallDrive(double sideMagnitude, double forwardMagnitude) {
    	// First, drive forward slightly to make sure the roller wheels will get traction against the wall
    	Robot.driveTrain.tankDrive(forwardMagnitude, forwardMagnitude); // Move at a small forward magnitude
    	// Arbitrarily define negative inputs as move left and positive as move right.
    	intakeMotorLeft.set ( sideMagnitude);   // for left  motor, negative input values will move us left and positive values will move us right
    	intakeMotorRight.set(-sideMagnitude); // for right motor, negative input values will move us right and negative values will move us left, so invert.
    }
}

