// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RecycleRush2015.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousGrandSlam extends CommandGroup {
    
    public  AutonomousGrandSlam() {

	// The plan:
	// 1) start with robot around our container (before match start)
	// 2) lift container
	addSequential(new LifterContainerSetpointGo());
	// 3a) Arm lifter
	addSequential(new LifterActiveMode());
	// 3b) Roller in
	addParallel(new CollectRollerIn());
	// 3c) drive forward enough to grab tote (and auto-lift)
	addParallel(new DriveWithLimits(3, 0.5, 0.75)); // Time, Distance, speed
	// Now we have both our container and our tote.
	
	
	// 4) Grab the second alliance's container so we can move it out of the way.
	addSequential(new DriveWithLimits(3, 2, 0.75)); // Time, Distance, speed.  This will just cause the collector to be sucked in against the tote we have.
	// 5) Now turn downfield...
	addSequential(new TurnDownfield());
	// 6) Drive into the Auto Zone
	addSequential(new DriveWithLimits(5, 9, 0.75)); // Time, Distance, speed.
	// 7) and spit it out!
	addSequential(new CollectRollerOut());
	// 8) Drive back to the tote line
	addSequential(new DriveWithLimits(5, 9, -0.75)); // Time, Distance, speed.	
	// 9a) Turn back towards the totes
	addSequential(new TurnInfield());
	// 9b) While reversing the roller back to an input configuration
	addParallel(new CollectRollerIn());
	
	
	// Get the second alliance's tote!
	// 10a) Arm lifter
	addSequential(new LifterActiveMode());
	// 10b) drive forward to get second tote
	addParallel(new DriveWithLimits(3, 1.5, 0.75)); // Time, Distance, speed
	// Now we should have collected the second tote and lifted it.
	
	
	// 11) Grab the third alliance's container and score it
	addSequential(new DriveWithLimits(3, 2, 0.75)); // Time, Distance, speed.  This will just cause the collector to be sucked in against the tote we have.
	// 12) Now turn downfield...
	addSequential(new TurnDownfield());
	// 13) Drive into the Auto Zone
	addSequential(new DriveWithLimits(5, 9, 0.75)); // Time, Distance, speed.
	// 14) and spit it out!
	addSequential(new CollectRollerOut());
	// 15) Drive back to the tote line
	addSequential(new DriveWithLimits(5, 9, -0.75)); // Time, Distance, speed.	
	// 16a) Turn back towards the totes
	addSequential(new TurnInfield());
	// 16b) While reversing the roller back to an input configuration
	addParallel(new CollectRollerIn());
	
	
	// Get the third alliance's tote!
	// 17a) arm lifter
	addSequential(new LifterActiveMode());
	// 17b) driver forward to get third tote
	addParallel(new DriveWithLimits(3, 1.5, 0.75));  // Time, Distance, speed
	// Now we should have collected the third tote and lifted it.
	
	
	// Now we have three totes and a container
	// Turn and go to the auto zone to complete our mission
	// 18) Turn 90'
	addSequential(new TurnDownfield());
	// 19) Go forward into the Auto Zone
	addSequential(new DriveWithLimits(3, 9, 0.75)); // Time, Distance, speed   	
	// 20) Drop stack
	addSequential(new LifterDropStack());
	// 21) Back up 2 feet
	addSequential(new DriveWithLimits(3, 2, 0.75));  // Time, Distance, speed
	// Done.
    }
}
