// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RecycleRush2015.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Autonomous3TotePlusContainer extends CommandGroup {
    
    public  Autonomous3TotePlusContainer() {
	    // The plan:
    	// 1) start with robot around our container (before match start)
    	// 2) lift container
    	addSequential(new LifterContainerSetpointGo());
    	// 3a) Arm lifter
    	addSequential(new LifterActiveMode());
    	// 3b) Roller in
    	addParallel(new CollectRollerIn());
    	// 3c) drive forward enough to grab tote (and auto-lift)
    	addSequential(new DriveWithLimits(3, 0.5, 0.75)); // Time, Distance, speed
	    // Now we have both our container and our tote.
	    // Get everyone elses's totes!
	    // This assumes that the other robots moved their containers out of the way.
    	// 4a) Arm lifter
    	addSequential(new LifterActiveMode());
		// 4b) drive forward to get second tote
    	addSequential(new DriveWithLimits(3, 3.5, 0.75)); // Time, Distance, speed
    	// Now we should have collected the second tote and lifted it.  Lather, rinse, repeat.
		// 5) arm lifter
    	addSequential(new LifterActiveMode());
		// 6) driver forward to get third tote
    	addSequential(new DriveWithLimits(3, 3.5, 0.75));  // Time, Distance, speed
    	// Now we have three totes and a container
    	// Turn and go to the auto zone to complete our mission
		// 7) Turn 90'
    	addSequential(new TurnDownfield());
		// 8) Go forward 9' or so
    	addSequential(new DriveWithLimits(3, 9, 0.75)); // Time, Distance, speed   	
		// 9) Drop stack
    	addSequential(new LifterDropStack());
		// 10) Back up 2 feet
    	addSequential(new DriveWithLimits(3, 3.5, 0.75));  // Time, Distance, speed
    	// Done.
    	
    }
}
