// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RecycleRush2015.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Autonomous3TotePlusContainerPlusMove2Container extends CommandGroup {
    
    public  Autonomous3TotePlusContainerPlusMove2Container() {
	    // The plan:
    	// 1) start with robot around our container (before match start)
    	// 2) lift container
    	addSequential(new LifterContainerSetpointGo());
    	// 3a) Arm lifter
    	addSequential(new LifterActiveMode());
    	// 3b) Roller in
    	addParallel(new CollectRollerIn());
    	// 3c) drive forward enough to grab tote (and auto-lift)
    	addParallel(new DriveWithLimits(3, 0.5, 0.75)); // Time, Distance, speed
	    // Now we have both our container and our tote.
    	
    	
    	// 4) Grab the second alliance's container so we can move it out of the way.
    	addSequential(new DriveWithLimits(3, 2, 0.75)); // Time, Distance, speed.  This will just cause the collector to be sucked in against the tote we have.
    	// 5) Now turn downfield...
    	addSequential(new TurnDownfield());
    	// 6) and spit it out!
    	addSequential(new CollectRollerOut());
    	// 7a) Turn back towards the totes
    	addSequential(new TurnInfield());
    	// 7b) While reversing the roller back to an input configuration
    	addParallel(new CollectRollerIn());
    	
    	
	    // Get the second alliance's tote!
    	// 8a) Arm lifter
    	addSequential(new LifterActiveMode());
		// 8b) drive forward to get second tote
    	addParallel(new DriveWithLimits(3, 1.5, 0.75)); // Time, Distance, speed
    	// Now we should have collected the second tote and lifted it.

    	
    	// 9) Grab the third alliance's container so we can move it out of the way.
    	addSequential(new DriveWithLimits(3, 2, 0.75)); // Time, Distance, speed.  This will just cause the collector to be sucked in against the tote we have.
    	// 10) Now turn downfield...
    	addSequential(new TurnDownfield());
    	// 11) and spit it out!
    	addSequential(new CollectRollerOut());
    	// 12a) Turn back towards the totes
    	addSequential(new TurnInfield());
    	// 12b) While reversing the roller back to an input configuration
    	addParallel(new CollectRollerIn());
   	
    	
	    // Get the third alliance's tote!
		// 13a) arm lifter
    	addSequential(new LifterActiveMode());
		// 13b) driver forward to get third tote
    	addParallel(new DriveWithLimits(3, 1.5, 0.75));  // Time, Distance, speed
    	// Now we should have collected the third tote and lifted it.
    	
    	
    	// Now we have three totes and a container
    	// Turn and go to the auto zone to complete our mission
		// 14) Turn 90'
    	addSequential(new TurnDownfield());
		// 15) Go forward into the Auto Zone
    	addSequential(new DriveWithLimits(3, 9, 0.75)); // Time, Distance, speed   	
		// 16) Drop stack
    	addSequential(new LifterDropStack());
		// 17) Back up 2 feet
    	addSequential(new DriveWithLimits(3, 2, 0.75));  // Time, Distance, speed
    	// Done.
    }
}
