// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RecycleRush2015.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc1735.RecycleRush2015.commands.AutonomousRobotSet;
import org.usfirst.frc1735.RecycleRush2015.Robot;

/**
 *
 */
public class  AutonomousDispatcher extends Command {
    // We need a baseclass pointer to the command we choose so we can cancel it later
    Command main_p;

    public AutonomousDispatcher() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	// "Option 0" is to "do nothing" in the list.  Handled by falling through the 'if' statements and doing none of them.
    	
    	// "Option 1" is to drive forward into the Auto Zone and then stop (a "Robot Set")
        if (Robot.AutoMode.getSelected().toString().equals("1")) {
            AutonomousRobotSet main = new AutonomousRobotSet();
            main_p = main;
            main.start();
        }
        // Again, if we select '0' as an option we fall through the 'if' statements and do nothing.
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        // Leave the dispatcher around until the underlying command has completed.
        // That way, the dispatcher sticks around until Autonomous is done
        // This will enable any cancellation of the command to be caught and forwarded to the underlying command.
        // isFinished() would be ideal, but it is a protected member.  Thus, we will try to use isRunning() instead.
        return main_p.isRunning(); 
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        // When cancelled, we need to cancel the command we initiated!
        main_p.cancel();
    }
}
