// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RecycleRush2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1735.RecycleRush2015.Robot;

/**
 *
 */
public class  WallDriveLeft extends Command {

    public WallDriveLeft() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collectorRoller);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // Command requires both collector and drivetrain to operate...
        requires(Robot.driveTrain);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//Robot.collectorRoller.wallDrive(-0.7, 0.4); // side and forward
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	// Only runs while button is pressed; release of button calls interrupted()...
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.collectorRoller.wallDrive(0, 0); // side, forward
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
